# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.7.6, generator: @autorest/python@5.12.6)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from copy import deepcopy
from typing import TYPE_CHECKING

from msrest import Deserializer, Serializer

from azure.core import PipelineClient

from . import models
from ._configuration import PyRunwayConfiguration
from .operations import AccountAssetOperations, AssetOperations, AuthenticationOperations, ClientOperations, ConnectionOperations, ContentOperations, EndpointAssetOperations, EnrollmentOperations, GroupOperations, InvitationOperations, JobOperations, JobThreadOperations, LogsOperations, RemoteShellOperations, RepositoryOperations, ResultsOperations, RoleOperations, RunnerOperations, SetOperations, TagOperations, UserOperations

if TYPE_CHECKING:
    # pylint: disable=unused-import,ungrouped-imports
    from typing import Any, Optional, Union

    from azure.core.rest import HttpRequest, HttpResponse

class PyRunway(object):    # pylint: disable=too-many-instance-attributes
    """PyRunway.

    :ivar account_asset: AccountAssetOperations operations
    :vartype account_asset: Runway.Python.operations.AccountAssetOperations
    :ivar asset: AssetOperations operations
    :vartype asset: Runway.Python.operations.AssetOperations
    :ivar authentication: AuthenticationOperations operations
    :vartype authentication: Runway.Python.operations.AuthenticationOperations
    :ivar client: ClientOperations operations
    :vartype client: Runway.Python.operations.ClientOperations
    :ivar connection: ConnectionOperations operations
    :vartype connection: Runway.Python.operations.ConnectionOperations
    :ivar content: ContentOperations operations
    :vartype content: Runway.Python.operations.ContentOperations
    :ivar endpoint_asset: EndpointAssetOperations operations
    :vartype endpoint_asset: Runway.Python.operations.EndpointAssetOperations
    :ivar enrollment: EnrollmentOperations operations
    :vartype enrollment: Runway.Python.operations.EnrollmentOperations
    :ivar group: GroupOperations operations
    :vartype group: Runway.Python.operations.GroupOperations
    :ivar invitation: InvitationOperations operations
    :vartype invitation: Runway.Python.operations.InvitationOperations
    :ivar job: JobOperations operations
    :vartype job: Runway.Python.operations.JobOperations
    :ivar job_thread: JobThreadOperations operations
    :vartype job_thread: Runway.Python.operations.JobThreadOperations
    :ivar logs: LogsOperations operations
    :vartype logs: Runway.Python.operations.LogsOperations
    :ivar remote_shell: RemoteShellOperations operations
    :vartype remote_shell: Runway.Python.operations.RemoteShellOperations
    :ivar repository: RepositoryOperations operations
    :vartype repository: Runway.Python.operations.RepositoryOperations
    :ivar results: ResultsOperations operations
    :vartype results: Runway.Python.operations.ResultsOperations
    :ivar role: RoleOperations operations
    :vartype role: Runway.Python.operations.RoleOperations
    :ivar runner: RunnerOperations operations
    :vartype runner: Runway.Python.operations.RunnerOperations
    :ivar set: SetOperations operations
    :vartype set: Runway.Python.operations.SetOperations
    :ivar tag: TagOperations operations
    :vartype tag: Runway.Python.operations.TagOperations
    :ivar user: UserOperations operations
    :vartype user: Runway.Python.operations.UserOperations
    :param platform:
    :type platform: str or ~Runway.Python.models.Enum6
    :param base_url: Service URL. Default value is 'https://portal.runway.host'.
    :type base_url: str
    """

    def __init__(
        self,
        platform=None,  # type: Optional[Union[str, "_models.Enum6"]]
        base_url="https://portal.runway.host",  # type: str
        **kwargs  # type: Any
    ):
        # type: (...) -> None
        self._config = PyRunwayConfiguration(platform=platform, **kwargs)
        self._client = PipelineClient(base_url=base_url, config=self._config, **kwargs)

        client_models = {k: v for k, v in models.__dict__.items() if isinstance(v, type)}
        self._serialize = Serializer(client_models)
        self._deserialize = Deserializer(client_models)
        self._serialize.client_side_validation = False
        self.account_asset = AccountAssetOperations(self._client, self._config, self._serialize, self._deserialize)
        self.asset = AssetOperations(self._client, self._config, self._serialize, self._deserialize)
        self.authentication = AuthenticationOperations(self._client, self._config, self._serialize, self._deserialize)
        self.client = ClientOperations(self._client, self._config, self._serialize, self._deserialize)
        self.connection = ConnectionOperations(self._client, self._config, self._serialize, self._deserialize)
        self.content = ContentOperations(self._client, self._config, self._serialize, self._deserialize)
        self.endpoint_asset = EndpointAssetOperations(self._client, self._config, self._serialize, self._deserialize)
        self.enrollment = EnrollmentOperations(self._client, self._config, self._serialize, self._deserialize)
        self.group = GroupOperations(self._client, self._config, self._serialize, self._deserialize)
        self.invitation = InvitationOperations(self._client, self._config, self._serialize, self._deserialize)
        self.job = JobOperations(self._client, self._config, self._serialize, self._deserialize)
        self.job_thread = JobThreadOperations(self._client, self._config, self._serialize, self._deserialize)
        self.logs = LogsOperations(self._client, self._config, self._serialize, self._deserialize)
        self.remote_shell = RemoteShellOperations(self._client, self._config, self._serialize, self._deserialize)
        self.repository = RepositoryOperations(self._client, self._config, self._serialize, self._deserialize)
        self.results = ResultsOperations(self._client, self._config, self._serialize, self._deserialize)
        self.role = RoleOperations(self._client, self._config, self._serialize, self._deserialize)
        self.runner = RunnerOperations(self._client, self._config, self._serialize, self._deserialize)
        self.set = SetOperations(self._client, self._config, self._serialize, self._deserialize)
        self.tag = TagOperations(self._client, self._config, self._serialize, self._deserialize)
        self.user = UserOperations(self._client, self._config, self._serialize, self._deserialize)


    def _send_request(
        self,
        request,  # type: HttpRequest
        **kwargs  # type: Any
    ):
        # type: (...) -> HttpResponse
        """Runs the network request through the client's chained policies.

        >>> from azure.core.rest import HttpRequest
        >>> request = HttpRequest("GET", "https://www.example.org/")
        <HttpRequest [GET], url: 'https://www.example.org/'>
        >>> response = client._send_request(request)
        <HttpResponse: 200 OK>

        For more information on this code flow, see https://aka.ms/azsdk/python/protocol/quickstart

        :param request: The network request you want to make. Required.
        :type request: ~azure.core.rest.HttpRequest
        :keyword bool stream: Whether the response payload will be streamed. Defaults to False.
        :return: The response of your network call. Does not do error handling on your response.
        :rtype: ~azure.core.rest.HttpResponse
        """

        request_copy = deepcopy(request)
        request_copy.url = self._client.format_url(request_copy.url)
        return self._client.send_request(request_copy, **kwargs)

    def close(self):
        # type: () -> None
        self._client.close()

    def __enter__(self):
        # type: () -> PyRunway
        self._client.__enter__()
        return self

    def __exit__(self, *exc_details):
        # type: (Any) -> None
        self._client.__exit__(*exc_details)
